In [2]:
import numpy as np

In [10]:
# Create a 1D array of numbers from 0 to 9.

arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(type(arr1))
print(arr1)
arr2 = np.arange(0, 10, 1)
print(type(arr2))
print(arr2)


<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [10]:
# Create a 3×3 numpy array of all True’s
#numpy.ones((2, 2)) or numpy.zeros((2, 2)) This will give 0 or 1 so to convert we have to provide data type
print(np.ones((3, 3), dtype=bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [13]:
# Given an array as input, print only odd numbers as output
arr = np.arange(0, 12, 1)
arr_temp = [arr[i] for i in arr if arr[i]%2!=0]
arr_temp

[1, 3, 5, 7, 9, 11]

In [16]:
# Replace all odd numbers in arr with -2
arr3 = np.arange(0, 10, 1)
np.where(arr3%2!=0, -2, arr3) 

array([ 0, -2,  2, -2,  4, -2,  6, -2,  8, -2])

In [17]:
# How to reshape an array?
arr4 = np.arange(0, 10, 1)
np.reshape(arr4,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
# Convert a 1D array to a 2D array with 2 rows
arr5 = np.arange(0, 10, 1)
np.reshape(arr5,(2,-1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
# Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples.
a = np.arange(1, 10, 1)
b1 = np.array([a[i-1]  for i in a if a[i-1]%2!=0])
b2 = np.array([a[i-1]*4  for i in a if a[i-1]%2!=0])
print(type(b1))
print(type(b2))
b = np.concatenate((b1,b2),axis=0)
b

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


array([ 1,  3,  5,  7,  9,  4, 12, 20, 28, 36])

In [25]:
# Given array, check if there are any null values and print them out. 
arr6 = np.array([1,2,3,np.nan])
np.isnan(arr6)

array([False, False, False,  True])

In [28]:
# How to replace all missing values with 0 in a numpy array?
arr7 = np.array([np.nan,1,2,3,np.nan])
np.nan_to_num(arr7) 

array([0., 1., 2., 3., 0.])

In [33]:
# How to find the count of each unique number in a NumPy array?
a = np.array([1,1,2,3,4,4,5,5])
c,d = np.unique(a,return_counts=True)
print(np.asarray((c, d)))

[[1 2 3 4 5]
 [2 1 1 2 2]]


In [39]:
# How to convert a numeric to a categorical (text) array?
x = np.array([1, 2, 2.5])
print (type(x))
print(x)
y = x.astype(str)
print(type(y))
print(y)

<class 'numpy.ndarray'>
[1.  2.  2.5]
<class 'numpy.ndarray'>
['1.0' '2.0' '2.5']


In [55]:
# Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both. 
arr = np.arange(99, 300, 1)
t = np.array([arr[i-99] for i in arr if ((arr[i-99]%5==0 or arr[i-99]%7==0) and ((arr[i-99]%5 + arr[i-99]%7) !=0))])
t

array([100, 110, 112, 115, 119, 120, 125, 126, 130, 133, 135, 145, 147,
       150, 154, 155, 160, 161, 165, 168, 170, 180, 182, 185, 189, 190,
       195, 196, 200, 203, 205, 215, 217, 220, 224, 225, 230, 231, 235,
       238, 240, 250, 252, 255, 259, 260, 265, 266, 270, 273, 275, 285,
       287, 290, 294, 295])

In [43]:
# Write a program to reverse an array and print (Don’t use inbuilt reverse functions)
x = np.array([1, 2, 2.5])
print(x)
np.flip(x)


[1.  2.  2.5]


array([2.5, 2. , 1. ])